openapi: 3.0.0
info:
  title: Duplicate Participation API
  version: 1.0.0
  description: The API where matching and lookups will occur
servers:
  - url: /v1
paths:
  /query:
    post:
      operationId: Query for Matches
      tags:
        - Match
      summary: Search for all matching PII records
      description: 'Queries all state databases for any PII records that are an exact match to the last name, date of birth, and social security number in the request body''s `query` property.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
              properties:
                query:
                  type: array
                  items:
                    type: object
                    required:
                      - first
                      - last
                      - dob
                      - ssn
                    properties:
                      first:
                        type: string
                        description: PII record's first name
                      middle:
                        type: string
                        description: PII record's middle name
                      last:
                        type: string
                        description: PII record's last name
                      ssn:
                        type: string
                        description: PII record's social security number
                        pattern: '^\d{3}-\d{2}-\d{4}$'
                      dob:
                        type: string
                        format: date
                        description: PII record's date of birth
            examples:
              All fields:
                description: 'An example request to query a single individual, with values for all fields'
                value:
                  query:
                    - first: string
                      middle: string
                      last: string
                      ssn: 000-00-0000
                      dob: '1970-01-01'
              Only requried fields:
                description: A request with values only for required fields
                value:
                  query:
                    - first: string
                      last: string
                      ssn: 000-00-0000
                      dob: '1970-01-01'
              Multiple Records:
                description: A request with multiple records
                value:
                  query:
                    - first: string
                      last: string
                      ssn: 000-00-0000
                      dob: '1970-01-01'
                    - first: string
                      last: string
                      ssn: 000-00-0001
                      dob: '1970-01-02'
      responses:
        '200':
          description: Successful response. Returns match response items.
          content:
            application/json:
              schema:
                type: object
                required:
                  - data
                properties:
                  data:
                    type: array
                    description: 'Array of match query response items. For every match query item provided in the request, a match response item is returned, even if no matches are found.'
                    required:
                      - index
                    properties:
                      index:
                        type: integer
                        description: 'The index of the request item that the response item corresponds to, starting from 0. Index is derived from the implicit order of match query request items provided in the request.'
                      lookup_id:
                        type: string
                        nullable: true
                        description: 'The identifier of the match request item, if a match is present. This ID can be used for looking up the PII of the original match request item.'
                      matches:
                        type: array
                        items:
                          type: object
                          required:
                            - last
                            - ssn
                            - dob
                          properties:
                            first:
                              type: string
                              description: First name
                            middle:
                              type: string
                              description: Middle name
                            last:
                              type: string
                              description: Last name
                            ssn:
                              type: string
                              description: Social Security number
                              pattern: '^\d{3}-\d{2}-\d{4}$'
                            dob:
                              type: string
                              format: date
                              description: Date of birth
                            state:
                              type: string
                              description: State/territory two-letter postal abbreviation
                            state_abbr:
                              type: string
                              description: 'State/territory two-letter postal abbreviation. Deprecated, superseded by `state`.'
                              deprecated: true
                            exception:
                              type: string
                              description: Placeholder for value indicating special processing instructions
                            case_id:
                              type: string
                              description: Participant's state-specific case identifier. Can be the same for multiple participants.
                            participant_id:
                              type: string
                              description: Participant's state-specific identifier. Is unique to the participant. Must not be social security number or any PII.
                            benefits_end_month:
                              type: string
                              pattern: '^\d{4}-\d{2}$'
                              example: 2021-01
                              description: Participant's ending benefits month
                            recent_benefit_months:
                              type: array
                              items:
                                type: string
                                pattern: '^\d{4}-\d{2}$'
                                example: 2021-01
                              minItems: 0
                              maxItems: 3
                              description: 'List of up to the last 3 months that participant received benefits, in descending order. Each month is formatted as ISO 8601 year and month. Does not include current benefit month.'
                            protect_location:
                              type: boolean
                              nullable: true
                              example: true
                              description: Location protection flag for vulnerable individuals. True values indicate that the individualâ€™s location must be protected from disclosure to avoid harm to the individual. Apply the same protections to true and null values.
              examples:
                Single:
                  description: A query for a single individual returning a single match
                  value:
                    data:
                      - index: 0
                        lookup_id: string
                        matches:
                          - first: string
                            middle: string
                            last: string
                            ssn: 000-00-0000
                            dob: '1970-01-01'
                            state: ea
                            state_abbr: ea
                            exception: string
                            case_id: string
                            participant_id: string
                            benefits_end_month: 2021-01
                            recent_benefit_months:
                              - 2021-05
                              - 2021-04
                              - 2021-03
                            protect_location: true
                None:
                  description: A query for a single individual returning no matches
                  value:
                    data:
                      - index: 0
                        lookup_id: null
                        matches: []
                Multiple:
                  description: A query for one individual returning multiple matches
                  value:
                    data:
                      - index: 0
                        lookup_id: string
                        matches:
                          - first: string
                            middle: string
                            last: string
                            ssn: 000-00-0000
                            dob: '1970-01-01'
                            state: eb
                            state_abbr: eb
                            exception: string
                            case_id: string
                            participant_id: string
                            benefits_end_month: 2021-01
                            recent_benefit_months:
                              - 2021-05
                              - 2021-04
                              - 2021-03
                            protect_location: true
                          - first: null
                            middle: null
                            last: string
                            ssn: 000-00-0000
                            dob: '1970-01-01'
                            state: ec
                            state_abbr: ec
                            exception: null
                            case_id: string
                            participant_id: null
                            benefits_end_month: null
                            protect_location: null
                MultipleRecords:
                  description: A query for two individuals returning one match for each individual
                  value:
                    data:
                      - index: 0
                        lookup_id: string
                        matches:
                          - $ref: '#/paths/~1query/post/responses/200/content/application~1json/examples/Multiple/value/data/0/matches/1'
                      - index: 1
                        lookup_id: string
                        matches:
                          - $ref: '#/paths/~1query/post/responses/200/content/application~1json/examples/Multiple/value/data/0/matches/1'
                MultipleRecordsOneMatch:
                  description: A query for two individuals returning no matches for one individual and a match for the other
                  value:
                    data:
                      - index: 0
                        lookup_id: null
                        matches: []
                      - index: 1
                        lookup_id: string
                        matches:
                          - $ref: '#/paths/~1query/post/responses/200/content/application~1json/examples/Multiple/value/data/0/matches/1'
        '400':
          description: Bad request. Missing one of the required properties in the request body.
  '/lookup_ids/{id}':
    get:
      operationId: Get Lookups by ID
      tags:
        - Lookup
      summary: Get the original match data related to a Lookup ID
      description: User can provide a Lookup ID and receive the match data associated with it
      responses:
        '200':
          description: Successful response. Returns original match query request item.
          content:
            application/json:
              schema:
                type: object
                required:
                  - data
                properties:
                  data:
                    $ref: '#/paths/~1query/post/requestBody/content/application~1json/schema/properties/query/items'
              examples:
                All:
                  description: A response showing a query with values for all fields
                  value:
                    data:
                      first: string
                      middle: string
                      last: string
                      ssn: 000-00-0000
                      dob: '1970-01-01'
                Required:
                  description: A response showing a query with values for only required fields
                  value:
                    data:
                      first: string
                      last: string
                      ssn: 000-00-0000
                      dob: '1970-01-01'
        '400':
          description: Bad request
        '404':
          description: Not found
security:
  - ApiKeyAuth: []
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Ocp-Apim-Subscription-Key
